Add 2D Texture Array support to RenderDevice
GameDevTecnico/cubos pull request #116
Opened 2022-02-19 02:17 UTC by joaopat98

2022-02-19 19:48 UTC, RiscadoA approved these changes

2022-02-20 22:06 UTC, joaopat98 commented
Depends on #120.

2022-04-10 12:47 UTC, RiscadoA requested changes

2022-04-10 12:47 UTC, RiscadoA commented on core/include/cubos/gl/render_device.hpp
> +            [[nodiscard]] TargetType getTargetType() const;
Remove nodiscards here

2022-04-10 20:39 UTC, RiscadoA approved these changes

2022-04-10 20:44 UTC, merged