Setup file structure and cmake for the core and engine API libraries
GameDevTecnico/cubos pull request #1205
Opened 2024-05-28 09:50 UTC by EdSwordsmith

# Description

Creates a new directory `api/` with two projects for the core and engine C API libraries. Both have their own CMakeLists.txt file and a samples directory which will probably be needed later for testing these new libraries.

## Checklist

- [x] Self-review changes.
- [ ] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.
- [ ] Add entry to the changelog's unreleased section.

2024-05-28 09:59 UTC, RiscadoA requested changes
Thanks for working on this :rocket: 
Could you also add a `module.dox` file to both the `include/cubos/api/core` and `include/cubos/api/engine` directories? You can just copy the ones in the non-api directories, and change their names (to core-api, engine-api) and descriptions to match them.
Forgot documentation was thing

2024-05-28 09:59 UTC, RiscadoA commented on api/core/include/cubos/api/core/api.h
> +/// @ingroup core
```suggestion
/// @ingroup core-api
```

2024-05-28 09:59 UTC, RiscadoA commented on api/core/include/cubos/api/core/api.h
> +/// @addtogroup core
```suggestion
/// @addtogroup core-api
```

2024-05-28 09:59 UTC, RiscadoA commented on api/engine/include/cubos/api/engine/api.h
> +/// @ingroup engine
```suggestion
/// @ingroup engine-api
```

2024-05-28 09:59 UTC, RiscadoA commented on api/engine/include/cubos/api/engine/api.h
> +/// @addtogroup engine
```suggestion
/// @addtogroup engine-api
```

2024-05-28 09:59 UTC, RiscadoA commented on api/core/samples/CMakeLists.txt
> +
```suggestion
```

2024-05-28 09:59 UTC, RiscadoA commented on api/engine/CMakeLists.txt
> +
```suggestion
```

2024-05-28 10:00 UTC, RiscadoA requested changes
One more thing: you should also add the new directories to the `docs/Doxyfile` directory, otherwise they won't be included in the generated docs.

2024-05-28 11:00 UTC, RiscadoA approved these changes
Other than the comments I just added, LGTM!

2024-05-29 14:14 UTC, teres4 approved these changes

2024-06-03 08:45 UTC, merged