Implement spans for metrics profiling
GameDevTecnico/cubos pull request #1268
Opened 2024-06-20 18:01 UTC by roby2014

# Description

See linked issue for proposed implementation, but in short:
- Create new namespace `tel` with metrics, tracing and logging.
- Create span utilities to keep track of scopes
- Associate metrics and logs to spans

## Checklist

- [ ] Self-review changes.
- [ ] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.
- [ ] Add entry to the changelog's unreleased section.

2024-09-29 15:22 UTC, RiscadoA requested changes
Thank you for working on this! Seems mostly good to me, just some nitpicks.
Also, you need to add a module.dox for the new `core-tel` module. Check out other modules (e.g cubos/core/gl/module.dox)

2024-09-29 15:22 UTC, RiscadoA commented on CHANGELOG.md
> +- Move metrics to telemetry namespace (#1265, **@roby2014**).
This should be moved to the previous ### Changes section, before the ### Fixed section.
Also, I think you can merge those two, specially considering they come from the same issue.

2024-09-29 15:22 UTC, RiscadoA commented on CHANGELOG.md
> +- Create global telemetry level (for tracing/logging) (#1265, **@roby2014**).
```suggestion
- Global telemetry level (for tracing/logging) (#1265, **@roby2014**).
```

2024-09-29 15:22 UTC, RiscadoA commented on CHANGELOG.md
> +- Implemented tracing (#1265, **@roby2014**).
```suggestion
- Spans for tracing and profiling (#1265, **@roby2014**).
```

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/level.hpp
> +
```suggestion
```

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/metrics.hpp
> +#define CUBOS_PROFILE() ::cubos::core::tel::ScopeProfiler _profilingTimeTracker(__FUNCTION__, __FILE__, __LINE__)
This is kind of useless now, no? Considering we now have spans
Should we remove it? We should only add the `begin` and `end` metrics to spans if `CUBOS_PROFILING` is enabled.

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +#include <chrono>
You're not using this here, so you can move it to the .cpp file

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +#define SPAN_INNER(a, b) a##b
You don't need these macros right?

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +    /// @brief A guard object that ensures a span ends when it goes out of scope.
```suggestion
    /// @brief A guard object that automatically ends the current span when it goes out of scope.
```

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +        std::size_t id;   ///< Unique identifier.
```suggestion
        std::size_t id;   ///< Identifier which distinguishes between instances of spans with the same path.
```
It's not really unique - two threads will produce spans with the same ids. Both fields are needed to get uniqueness.

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +    /// @brief Represents the unique identifier and path for a span.
```suggestion
    /// @brief Uniquely identifies a span.
```

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +        SpanManager() = default;
```suggestion
```
You end up not instantiating objects of this class, so you can remove this

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +        static void level(Level level);
```suggestion
```
Redundant now, as we already have the global level function.

2024-09-29 15:22 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +        /// @param s Pointer to the span to be entered.
```suggestion
        /// @param name Span name.
        /// @param level Span level.
```

2024-09-29 15:22 UTC, RiscadoA commented on core/samples/tel/metrics/page.md
> +Registering metrics and profiling in **CUBOS.** can be done through the metric macros defined in @ref core/tel/metrics.hpp and the @ref core::tel::Metrics class.
```suggestion
Registering metrics and profiling in **Cubos** can be done through the metric macros defined in @ref core/tel/metrics.hpp and the @ref core::tel::Metrics class.
```

2024-09-29 18:16 UTC, RiscadoA requested changes

2024-09-29 18:16 UTC, RiscadoA commented on core/include/cubos/core/tel/tracing.hpp
> +        /// @return Span* Pointer to the current active span.
```suggestion
        /// @return Identifier of the current span.
```

2024-10-01 12:59 UTC, diogomsmiranda approved these changes
I don't see much code of this part of CUBOS so can't be of much help, but looks like most of files changed were just refactor of the code to fit the new namespace. Found nothing very wrong when looking at the implementation and docs.
If all the other requested changes were already addressed then LGTM!

Very useful feature aswell!!

2024-10-07 19:32 UTC, RiscadoA approved these changes
LGTM! Ty for the crunch :pray:

2024-10-09 09:03 UTC, Dageus approved these changes

2024-10-10 19:33 UTC, merged