Transition to TGS Soft impulse solver
GameDevTecnico/cubos pull request #1273
Opened 2024-06-28 16:16 UTC by fallenatlas

# Description

Oh boy...

Transition from XPBD solver to TGS solver.

Much of the solver for the penetration constraints was changed, we now make corrections based on impulses, based mainly on the equations for conservation of momentum with some bias proportional to the penetration which will work to separate the particles.

Collisions also work as soft constraints now, the values might need some tweaking in the future but they seem ok for now.

The integration also had to be changed and is now under the solver, because it just makes more sense.

The new loop is as follows:

- fixed step
  - collision stuff (unchanged)
  - prepare constraints (for now just create the penetration constraint for colliding pairs)
  - fixed substep
    - integrate velocity
    - solve velocity with bias
    - integrate position
    - solve velocity without bias (relax)
  - finalize position (apply position correction)

Currently the impulses are enough only to separate the particles, this means that some collisions may not look as expected because everything is perfectly inelastic. Elastic and inelastic collisions will come with restitution which should be the next PR.

Also of note that stacks of more than 2 particles aren't very good yet, so the complex physics sample won't look the best.

## Checklist

- [x] Self-review changes.
- [x] Evaluate impact on the documentation.
- [x] Add entry to the changelog's unreleased section.

2024-06-28 17:39 UTC, RiscadoA requested changes
Thanks for working on this! That was very quick :eyes: good job!

2024-06-28 17:39 UTC, RiscadoA commented on engine/include/cubos/engine/physics/plugin.hpp
```suggestion

    /// @brief Tag which should be used on all systems that modify velocity or apply forces or impulses.
```

2024-06-28 17:39 UTC, RiscadoA commented on engine/src/physics/solver/integration/plugin.cpp
> +void cubos::engine::integrationPlugin(Cubos& cubos)
```suggestion
void cubos::engine::physicsIntegrationPlugin(Cubos& cubos)
```

2024-06-28 17:39 UTC, RiscadoA commented on engine/samples/complex-physics/main.cpp
Just noticed the folder name doesn't follow the convention, it should be complex_physics.

2024-06-28 17:39 UTC, RiscadoA commented on engine/src/physics/plugin.cpp
>      cubos.plugin(fixedSubstepPlugin);
This plugin should be prefixed with `physics`.

2024-06-29 08:44 UTC, DiogoMendonc-a approved these changes
LGTM, but to be fair, I don't really know what I'm looking at for most of these maths 😅

2024-06-29 19:06 UTC, tomas7770 approved these changes
LGTM as far as I can understand!

2024-06-29 20:41 UTC, RiscadoA approved these changes
Other than the comments I added, LGTM!

2024-06-29 20:41 UTC, RiscadoA commented on engine/include/cubos/engine/physics/plugin.hpp
> +    ///
```suggestion
```

2024-06-29 20:41 UTC, RiscadoA commented on engine/src/physics/solver/plugin.cpp
>  void cubos::engine::solverPlugin(Cubos& cubos)
```suggestion
void cubos::engine::physicsSolverPlugin(Cubos& cubos)
```

2024-06-30 18:02 UTC, merged