feat(debug-camera): add way of changing speed of the debug camera usi…
GameDevTecnico/cubos pull request #1286
Opened 2024-07-16 21:25 UTC by diogomsmiranda

…ng tab and LShift

# Description

Include a summary of the changes here.

## Checklist

- [ ] Self-review changes.
- [ ] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.
- [ ] Add entry to the changelog's unreleased section.

2024-07-17 09:32 UTC, RiscadoA requested changes
Thanks for the quick work :relieved: just make sure to change the scope to `tesseratos` instead of `debug-camera` before merging, otherwise LGTM!

2024-07-17 21:24 UTC, diogomsmiranda commented
> Thanks for the quick work 😌 just make sure to change the scope to `tesseratos` instead of `debug-camera` before merging, otherwise LGTM!

Changes addressed.

2024-07-17 22:24 UTC, RiscadoA approved these changes

2024-07-18 18:13 UTC, roby2014 approved these changes

2024-07-18 22:10 UTC, merged