1292 allow importing voxel models through the asset explorer
GameDevTecnico/cubos pull request #1299
Opened 2024-08-02 23:32 UTC by Scarface1809

# Description

Allow Importing .grd & .pal files via new VoxelModel assets.

2024-08-02 23:34 UTC, Scarface1809 commented
Still unfinished, só para reviewers verem e apontarem anything I may be doing wrong.

2024-08-07 08:47 UTC, DiogoMendonc-a approved these changes

2024-08-07 08:47 UTC, DiogoMendonc-a commented on engine/src/assets/assets.cpp
> +    // Skip files that already have a .meta extension.
```suggestion
    // Skip meta files.
```
I got confused at first, because I'd interpreted this as meaning files for which the meta file exists.

2024-08-07 08:47 UTC, DiogoMendonc-a commented on engine/src/voxels/voxel_model.cpp
> +                            if (mat >= 65536)
This should probably be a const somewhere, no?

2024-10-01 07:02 UTC, RiscadoA requested changes
Thanks very much for working on this! This tool will be really useful :eyes:
I tried giving it a go locally and it fails to open the `car.qb` (Unsupported version 0.0.0.0, only 1.1.0.0 is supported), which is weird :thinking: is the asset you included valid?

2024-10-04 16:47 UTC, RiscadoA approved these changes
Other than these final comments I added, LGTM!
Ty very much for working on this!
Looking forward to not having to use quadrados for the next demo :eyes:

2024-10-04 16:47 UTC, RiscadoA commented on engine/include/cubos/engine/voxels/model.hpp
> +        void gridPosition(std::size_t index, glm::ivec3 position);
Make sure to document these methods so that they appear in the documentation website!

2024-10-04 16:47 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/importer/plugin.cpp
> +    assets.writeMeta(state.currentAsset)->set("palette_id", uuids::to_string(paletteHandle.getId()));
```suggestion
    assets.writeMeta(state.currentAsset)->set("paletteId", uuids::to_string(paletteHandle.getId()));
```
Just for consistency with the other json files we have

2024-10-04 16:47 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/importer/plugin.cpp
> +            ->set("grid_id_" + std::to_string(i), uuids::to_string(gridHandles[i].getId()));
```suggestion
            ->set("grid" + std::to_string(i) + "Id", uuids::to_string(gridHandles[i].getId()));
```
Same as above

2024-10-04 16:47 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/importer/plugin.cpp
> +        assets.writeMeta(state.currentAsset)
Shouldn't you skip handles for which `gridHandles[i].isNull()` is true here? (You do so above)

2024-10-05 07:46 UTC, RiscadoA commented on engine/CMakeLists.txt
Don't forget to:
- add an entry to the CHANGELOG.md
- tidy your commits! Your first commits have the wrong casing - the first character of the message. should be lowercase. Also, don't keep around commits like 'fix clang tidy' 'fix build errors'. Try squashing these into the main commits so that we have a clean git history

2024-10-06 12:59 UTC, roby2014 requested changes

2024-10-06 12:59 UTC, roby2014 commented on tools/tesseratos/src/tesseratos/importer/plugin.cpp
> +                    CUBOS_INFO("Creating new grid asset.");
```c++
CUBOS_INFO("Creating new grid asset");
```

2024-10-07 08:19 UTC, roby2014 approved these changes

2024-10-07 10:50 UTC, merged