added target executable for `tesserato` editor tool
GameDevTecnico/cubos pull request #276
Opened 2022-12-14 16:34 UTC by roby2014

- changed `tools/` folder structure
- updated readme

2022-12-14 16:38 UTC, RiscadoA commented on tools/tesserato/CMakeLists.txt
> +# Cubos tools (tesserato) build configuration
```suggestion
# Ttesserato build configuration
```

2022-12-14 22:00 UTC, rsubtil commented
It's a good idea to bootstrap the base editor already, instead of a blank hello world. The current structure on the scene sample is a good start:
https://github.com/GameDevTecnico/cubos/blob/8656d1fee68b2ae1c89a1033eb0b10fb3de8e670/engine/samples/scene/main.cpp#L48-L62
But in this case only the two plugins should be added, since that's what we have so far.

2022-12-14 22:49 UTC, roby2014 commented
Sounds good to me.

2022-12-15 17:16 UTC, RiscadoA requested changes

2022-12-15 17:16 UTC, RiscadoA commented on tools/tesserato/CMakeLists.txt
> +target_link_libraries(tesserato PUBLIC cubos-engine)
You can merge the two lines.
```suggestion
target_link_libraries(tesserato PUBLIC cubos-core cubos-engine)
```

2022-12-15 19:50 UTC, RiscadoA commented on tools/tesserato/CMakeLists.txt
> +target_link_libraries(tesserato PUBLIC cubos-core)
You also need to remove this line (I couldn't remove it in the suggestion for some reason).

2022-12-16 08:31 UTC, RiscadoA approved these changes

2022-12-18 08:45 UTC, merged