[WIP] Add Settings Inspector plugin
GameDevTecnico/cubos pull request #280
Opened 2022-12-15 14:20 UTC by roby2014

Depends on #279

2022-12-15 14:21 UTC, roby2014 commented
UI needs polishing, but the "inspect" part already works.

2022-12-17 20:52 UTC, RiscadoA requested changes

2022-12-17 20:52 UTC, RiscadoA commented on engine/include/cubos/engine/plugins/settings_inspector.hpp
> +    void settingsInspectorPlugin(Cubos& cubos);
I would just move this into another namespace and directory, maybe `plugins::tools`? Not sure what we would name it.

2022-12-21 07:58 UTC, RiscadoA approved these changes

2023-01-08 18:40 UTC, merged