Add `ConstructibleTrait`
GameDevTecnico/cubos pull request #500
Opened 2023-09-05 16:46 UTC by RiscadoA

Blocked by #494 and #487.

# Description

Adds the `ConstructibleTrait`.

## Checklist

- [ ] Self-review changes.
- [X] Evaluate impact on the documentation.
- [X] Ensure test coverage.
- [X] Write new samples.

2023-09-14 11:08 UTC, DiogoMendonc-a submitted a review, later dismissed

2023-09-17 16:15 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/constructible_utils.hpp
> +        if (std::is_default_constructible<T>::value)
```suggestion
        if constexpr (std::is_default_constructible<T>::value)
```

2023-09-17 16:15 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/constructible_utils.hpp
> +        if (std::is_copy_constructible<T>::value)
```suggestion
        if constexpr (std::is_copy_constructible<T>::value)
```

2023-09-17 16:15 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/constructible_utils.hpp
> +        if (std::is_move_constructible<T>::value)
```suggestion
        if constexpr (std::is_move_constructible<T>::value)
```

2023-09-17 17:23 UTC, luishfonseca requested changes

2023-09-17 17:23 UTC, luishfonseca commented on core/include/cubos/core/reflection/traits/constructible.hpp
The obfuscation of std::move make this code hard to read, either use <utility> or move the complexity to an header file in core/memory

2023-09-17 17:23 UTC, luishfonseca commented on core/include/cubos/core/reflection/traits/constructible_utils.hpp
see previous comment about std::move

2023-09-19 16:15 UTC, RiscadoA commented on core/samples/reflection/traits/constructible/page.md
> +You may find it useful while working with type-erased data to be able to create
Explained it in the module's page and linked it in the reflection examples root page.

2023-09-19 19:42 UTC, luishfonseca approved these changes

2023-09-19 19:47 UTC, merged