Add `ArrayTrait`
GameDevTecnico/cubos pull request #546
Opened 2023-09-16 18:33 UTC by RiscadoA

Blocked by #500 and #543.

# Description

Adds the `ArrayTrait` and defines reflection for `std::vector<T>` types.

## Checklist

- [ ] Self-review changes.
- [X] Evaluate impact on the documentation.
- [X] Ensure test coverage.
- [X] Write new samples.

2023-09-20 20:13 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/array.hpp
> +        /// @note Aborts if @ref hasInsertCopy() returns false.
```suggestion
```
Outdated, applies to other inserts and erase.

2023-09-21 12:07 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/array.hpp
> +        /// @note Aborts if @ref hasInsertMove() returns false.
```suggestion
```

2023-09-21 12:07 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/array.hpp
> +        /// @note Aborts if @ref hasErase() returns false.
```suggestion
```

2023-09-21 12:07 UTC, RiscadoA commented on core/include/cubos/core/reflection/traits/array.hpp
> +        /// @note Aborts if @ref hasInsertDefault() returns false.
```suggestion
```

2023-09-21 17:06 UTC, luishfonseca requested changes

2023-09-22 15:59 UTC, RiscadoA commented on core/samples/reflection/traits/array/main.cpp
> +    if (!arrayTrait.elementType().is<int>())
```suggestion
    if (!arrayTrait.elementType().is<int32_t>())
```

2023-09-22 15:59 UTC, RiscadoA commented on core/samples/reflection/traits/array/main.cpp
> +        CUBOS_INFO("Element {}: {}", i, *static_cast<const int*>(arrayTrait.get(instance, i)));
```suggestion
        CUBOS_INFO("Element {}: {}", i, *static_cast<const int32_t*>(arrayTrait.get(instance, i)));
```

2023-09-22 16:22 UTC, RiscadoA commented on core/samples/reflection/traits/array/page.md
> +reflecting the type `std::vector<int>`, which also means reflecting `int`.
```suggestion
reflecting the type `std::vector<int32_t>`, which also means reflecting `int32_t`.
```

2023-09-22 16:22 UTC, RiscadoA commented on core/samples/reflection/traits/array/page.md
> +In this example, we're only supporting arrays of `int`s, but we could for
```suggestion
In this example, we're only supporting arrays of `int32_t`s, but we could for
```

2023-09-25 11:00 UTC, luishfonseca requested changes

2023-09-25 11:00 UTC, luishfonseca commented on core/samples/reflection/traits/array/main.cpp
>          CUBOS_INFO("This function does not support printing arrays of types other than int");
```suggestion
        CUBOS_INFO("This function does not support printing arrays of types other than int32_t");
```

2023-09-27 13:25 UTC, luishfonseca reviewed
Should we add `.view(...)`? It would allow the following syntax
```cpp
for (auto* value : arrayTrait.view(myArray))
{
...
}
```

2023-09-28 09:47 UTC, luishfonseca approved these changes

2023-09-28 09:58 UTC, merged