docs(engine): document Input sample
GameDevTecnico/cubos pull request #580
Opened 2023-09-25 09:42 UTC by DiogoMendonc-a

2023-09-25 10:47 UTC, luishfonseca requested changes
This sample is overcomplicated (my bad), some suggestions to simplify it:

2023-09-25 10:47 UTC, luishfonseca commented on engine/samples/input/page.md
> +You can also just get the modifier keys on their own in the same manner.
The sample is overcomplicated and is showcasing modifier behaviour that will be reworked. For now this snippet, should be removed along with the related bindings as they're an hack.

2023-09-25 10:47 UTC, luishfonseca commented on engine/samples/input/page.md
> +@include assets/sample.bind
This file is way too long to be included, I would remove some actions. I think we can have only the `next-showcase`, `x-or-z`, `shift-space`, `ctrl-shift-space` actions (see other review as why to remove last two actions). Please adapt the sample accordingly.

2023-09-27 09:44 UTC, luishfonseca approved these changes

2023-09-28 08:31 UTC, RiscadoA approved these changes

2023-09-28 08:32 UTC, merged