Asset is nuked when save fails
GameDevTecnico/cubos pull request #739
Opened 2023-10-17 17:58 UTC by roby2014

# Description

Added `FileSystem::copy` and basically it tries to create a `.swp` file and save the contents there. In case it fails, nothing happens to the original asset file. If everything goes right, we copy the contents from `.swp` to the original file

## Checklist

- [X] Self-review changes.
- [X] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.

2023-10-17 18:00 UTC, roby2014 commented
Eh I guess we should delete the `.swp` file after copying right

2023-10-22 08:23 UTC, RiscadoA approved these changes
Thanks for working on this! Pointed out some minor nitpicks, but LGTM!

2023-10-22 08:23 UTC, RiscadoA commented on core/include/cubos/core/data/fs/file_system.hpp
> +        /// @param destinationPath The absolute path of the destination file.
```suggestion
        /// @param sourcePath Absolute path of the source file.
        /// @param destinationPath Absolute path of the destination file.
```

2023-10-22 08:23 UTC, RiscadoA commented on core/include/cubos/core/data/fs/file_system.hpp
> +        /// @return `true` if the file was successfully copied; `false` if an error occurred.
```suggestion
        /// @return Whether the file was successfully copied.
```

2023-10-22 08:23 UTC, RiscadoA commented on core/src/cubos/core/data/fs/file_system.cpp
> +        CUBOS_ERROR("Failed to open source stream");
```suggestion
        CUBOS_ERROR("Could not open source file '{}' for copying", sourcePath);
```

2023-10-22 08:23 UTC, RiscadoA commented on core/src/cubos/core/data/fs/file_system.cpp
> +        CUBOS_ERROR("Failed to create destination file '{}'", destinationPath);
```suggestion
        CUBOS_ERROR("Could not create destination file '{}' for copying", destinationPath);
```

2023-10-22 08:23 UTC, RiscadoA commented on core/src/cubos/core/data/fs/file_system.cpp
> +        CUBOS_ERROR("Failed to open destination stream");
```suggestion
        CUBOS_ERROR("Could not open destination file '{}' for copying", destinationPath);
```

2023-10-22 08:23 UTC, RiscadoA commented on core/src/cubos/core/data/fs/file_system.cpp
> +        }
Ig that since you added the while !eof condition to the while loop this if should not be necessary

2023-10-22 10:44 UTC, RiscadoA requested changes
This definitely needs to be tested, forgot about that mb

2023-10-30 07:57 UTC, RiscadoA approved these changes
Thanks for working on this! :)

2023-10-30 07:57 UTC, RiscadoA commented on core/include/cubos/core/data/fs/file_system.hpp
> +        /// @return Whether  was successfully copied.
```suggestion
        /// @return Whether the file was successfully copied.
```

2023-10-30 07:57 UTC, RiscadoA commented on core/src/cubos/core/data/fs/file.cpp
> +    }
The condition seems unnecessary, I think `file` can never be null, right?

2023-10-30 07:57 UTC, RiscadoA commented on engine/src/cubos/engine/assets/bridges/file.cpp
> +        CUBOS_ERROR("Could not save asset {}", path);
```suggestion
        CUBOS_ERROR("Could not overwrite asset with swap file", path);
```

2023-10-30 08:01 UTC, RiscadoA commented on core/tests/data/fs/file_system.cpp
> +            REQUIRE_FALSE(FileSystem::copy("/bar/nonexistent", "/bar/newfiledoesntmatter"));
Would also be nice to cover cases such as copying to somewhere read-only (e.g., outside the archive).
```suggestion
            REQUIRE_FALSE(FileSystem::copy("/dir/sub/arc/bar/nonexistent", "/dir/sub/arc/bar/newfiledoesntmatter"));
            REQUIRE_FALSE(FileSystem::copy(baz->path(), "/dir/readonlyfile"));
```

2023-10-31 18:46 UTC, RiscadoA requested changes
It seems some of the stuff you had resolved previously broke with your recent changes, can you take a look at it again?

2023-10-31 21:01 UTC, RiscadoA approved these changes

2023-10-31 21:11 UTC, merged