Implement DataInspector, using the new reflection system
GameDevTecnico/cubos pull request #779
Opened 2023-11-05 19:10 UTC by roby2014

# Description

Implemented DataInspector, using the new reflection system, to replace the Package stuff

## Checklist

- [X] Self-review changes.
- [X] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [X] Write new samples.

2023-11-05 19:32 UTC, RiscadoA requested changes
Thanks for working on this @roby2014! One step closer to getting rid of the old namespace :eyes:

2023-11-05 19:32 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        using Type = core::reflection::Type;
I think its best to omit the alias here, its just some extra characters in the methods and it won't ever be used through the class elsewhere.

2023-11-05 19:32 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +         */
Use triple slash docs style (same in other funcs)

2023-11-05 19:32 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +} // namespace cubos::engine
Add missing new line at EOF

2023-11-05 19:32 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +    /// @brief Resource which allows user to inspect or modify object's properties in the UI.
```suggestion
    /// @brief Resource which allows the user to inspect or modify any reflectable value in the UI.
```

2023-11-05 19:32 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +    ///
```suggestion
    /// @see Take a look at the @ref examples-engine-imgui example for a demonstration of this resource.
```

2023-11-05 19:32 UTC, RiscadoA commented on engine/samples/data_inspector/main.cpp
I would make this part of the ImGui sample

2023-11-05 19:32 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
I think you should, as we discussed previously, replace these static show/edit functions for static inspect functions, which take a non-const pointer to the value and a bool indicating whether the operation is readOnly.

2023-11-08 19:57 UTC, roby2014 commented
Looks good for a review. Next step would be to remove the old serialization method and use the new resource on the Entity inspector plugin & etc... Can I do that in this PR as well?

2023-11-08 21:42 UTC, RiscadoA commented
Ty! Will review friday. I think its best to leave it to another PR - you can rebase it on this one

2023-11-13 08:59 UTC, RiscadoA requested changes
Thanks for working on this @roby2014! Good work :) One of the next steps we should worry about concerning this section of the code is allowing users of data inspector to register custom behavior for their types. That might require some changes later on, but it will be mostly restructuring methods and most of the code you wrote will remain the same.

2023-11-13 08:59 UTC, RiscadoA commented on core/include/cubos/core/memory/any_value.hpp
>          /// constructible.
```suggestion
        /// @note @p type must have @ref reflection::ConstructibleTrait and be default
        /// constructible.
```

2023-11-13 08:59 UTC, RiscadoA commented on core/include/cubos/core/memory/any_value.hpp
> +        /// @note mType member must not be null.
```suggestion
        /// @note @ref valid() must return true. 
```

And add a method `bool valid() const` which returns whether a value is held (`mType != nullptr`).

2023-11-13 08:59 UTC, RiscadoA commented on core/src/cubos/core/memory/any_value.cpp
> +    CUBOS_ASSERT(mType != nullptr, "Type must not be null");
```suggestion
    CUBOS_ASSERT(this->valid(), "This must hold a value");
```

2023-11-13 08:59 UTC, RiscadoA commented on core/src/cubos/core/memory/any_value.cpp
>  void* AnyValue::get()
Change the get methods to also assert `this->valid`

2023-11-13 08:59 UTC, RiscadoA commented on core/tests/memory/any_value.cpp
> +            CHECK(*static_cast<int*>(any.get()) == value);
I would change this to
```suggestion
            int value = 1337;
            AnyValue any{};
            REQUIRE_FALSE(any.valid());
            any = AnyValue::moveConstruct(reflect<int>(), &value);
            REQUIRE(any.valid());
            CHECK(any.type().is<int>());
            CHECK(*static_cast<int*>(any.get()) == value);
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        bool inspect(const std::string& name, const core::reflection::Type& type, void* value, bool readOnly = true);
I would keep inspect something internal and here have only `show` and `edit`, show receiving `const void*`. This way the user doesn't have to use const_cast.

2023-11-13 08:59 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        cubos::core::memory::AnyValue mValue;
Usually we put the private fields below the private methods

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/img2.png
Isn't the map missing 'remove' buttons? Also, are we keeping labels on both columns then?

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/main.cpp
> +using cubos::engine::DataInspector;
```suggestion
using cubos::core::reflection::reflect;

using cubos::engine::DataInspector;
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/main.cpp
> +    return cubos::core::reflection::Type::create("Person").with(cubos::core::reflection::FieldsTrait()
```suggestion
    return Type::create("Person").with(FieldsTrait()
```

Add using statements for this

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/main.cpp
> +static void fillDumyResourceSystem(Write<DummyResource> data)
```suggestion
static void fillDummyResourceSystem(Write<DummyResource> data)
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        bool inspect(const std::string& name, const core::reflection::Type& type, void* value, bool readOnly = true);
Would also be cool to add template methods with signatures `show(const std::string& name, const T& value);` which call reflect for us.

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/main.cpp
> +    inspector->inspect("data->map", mapType, (void*)&data->map, false);
If you add the templated show/edit methods, you no longer need those static vars above

2023-11-13 08:59 UTC, RiscadoA commented on engine/samples/imgui/main.cpp
> +    cubos.addResource<DummyResource>();
You could initialize the resource here btw, and thus remove the need for a startup system:
```suggestion
    cubos.addResource<DummyResource>(DummyResource{
        .integer = 1337,
        /*...*/
    });
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +    else
I think you need to handle `StringConversionTrait` here: for example, `RenderableGrid` components contain a `Asset<Grid>` field which only provides that trait.

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +}
Missing newline at EOF

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +    auto str = getPrimitiveValue(value, type);
Wait what is this being used for?

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +void DataInspector::showStructured(const std::string& name, const Type& type, auto fn)
Maybe rename this method to `withStructure` or something since it is both used 'edit' and 'show' methods.

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +        return *(bool*)(value) ? "true" : "false";
```suggestion
        return *static_cast<bool*>(value) ? "true" : "false";
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +        return std::to_string(*(TYPE*)(value));                                                                        \
```suggestion
        return std::to_string(*static_cast<TYPE*>(value));                                                                        \
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +    CUBOS_ERROR("Could not get primitive object as formatted string (unknown primitive).");
```suggestion
    CUBOS_ERROR("Expected value with primitive type, found unsupported type '{}'", type.name());
```

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/data_inspector.cpp
> +    return modified;
You should give an error and show ??? or something if the type is unsupported here, right now you just return without doing anything

2023-11-13 08:59 UTC, RiscadoA commented on engine/src/cubos/engine/imgui/plugin.cpp
> +    cubos.addResource<DataInspector>();
You should also add this resource to the imgui plugin docs on the `## Resources` section (see other plugins)

2023-11-13 11:44 UTC, roby2014 commented on engine/samples/imgui/img2.png
Yeah my bad. 
Labels cant be removed, since they work like an "id" for the input scalars etc.. (we can removeit but then we would have to work with pushid pop id every input scalar, what do you prefer?

2023-11-13 11:46 UTC, RiscadoA commented on engine/samples/imgui/img2.png
Hmm. I prefer `PushId` `Pop`, although it is a nuisance code wise, having the labels repeated everywhere is triggering my OCD

2023-11-13 14:15 UTC, roby2014 commented
> Thanks for working on this @roby2014! Good work :) One of the next steps we should worry about concerning this section of the code is allowing users of data inspector to register custom behavior for their types. That might require some changes later on, but it will be mostly restructuring methods and most of the code you wrote will remain the same.

Do you want to handle that custom type behaviour also in this PR?

2023-11-13 14:21 UTC, RiscadoA commented
> > Thanks for working on this @roby2014! Good work :) One of the next steps we should worry about concerning this section of the code is allowing users of data inspector to register custom behavior for their types. That might require some changes later on, but it will be mostly restructuring methods and most of the code you wrote will remain the same.
> 
> Do you want to handle that custom type behaviour also in this PR?

Nope, lets leave that for another PR. This one is already really large

2023-11-13 14:26 UTC, roby2014 commented
> > > Thanks for working on this @roby2014! Good work :) One of the next steps we should worry about concerning this section of the code is allowing users of data inspector to register custom behavior for their types. That might require some changes later on, but it will be mostly restructuring methods and most of the code you wrote will remain the same.
> > 
> > 
> > Do you want to handle that custom type behaviour also in this PR?
> 
> Nope, lets leave that for another PR. This one is already really large

Alright, opened a tracking issue: #810

2023-11-13 15:01 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        /// @return True if object was modified.
```suggestion
        /// @brief Displays a reflectable value on the UI, optionally allowing modification.
        /// @param name Value name.
        /// @param type Value type.
        /// @param value Pointer to value.
        /// @param readOnly Whether the value can be modified.
        /// @return Whether the value was modified.
```

2023-11-13 15:03 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        /// open.
```suggestion
        /// @brief Displays a structured value inside a `ImGui::TreeNode`.
        /// @param name Value name.
        /// @param type Value type.
        /// @param fn Functor called when the node is open.
```

2023-11-13 15:06 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        void showPrimitiveObject(const std::string& name, const core::reflection::Type& type, const void* value);
```suggestion
        /// @brief Displays a value of a known type, or "???" if its unknown.
        /// @param name Value name.
        /// @param type Value type.
        /// @param value Pointer to value.
        void showKnown(const std::string& name, const core::reflection::Type& type, const void* value);
```

2023-11-13 15:07 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        std::string getPrimitiveValue(const void* value, const core::reflection::Type& type);
```suggestion
        /// @brief Gets a representative string for a value of a known type, or "???" if its unknown.
        ///
        /// @param name The name of the object.
        /// @param type The reflection type of the object.
        /// @param value A const pointer to the object's value.
        /// @return String that represents primitive value.
        std::string stringKnown(const void* value, const core::reflection::Type& type);
```

2023-11-13 15:10 UTC, RiscadoA commented on engine/include/cubos/engine/imgui/data_inspector.hpp
> +        bool editPrimitive(const std::string& name, const core::reflection::Type& type, void* value);
```suggestion
        /// @brief Displays a value of a known type, or "???" if its unknown. Allows modification.
        /// @param name Value name.
        /// @param type Value type.
        /// @param value Pointer to value.
        /// @return Whether the value was modified.
        bool editKnown(const std::string& name, const core::reflection::Type& type, void* value);
```

2023-11-13 21:57 UTC, merged

2023-11-13 23:00 UTC, roby2014 commented
todo: dictionary iterators tests