Integrate `DataInspector` and remove old serialization method
GameDevTecnico/cubos pull request #785
Opened 2023-11-09 08:27 UTC by roby2014

# Description

Related to #748

- Removed old serialization methods 
- Refactor entity inspector + settings inspector plugins to use the new `DataInspector`

## Checklist

- [X] Self-review changes.
- [X] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.

2023-11-13 09:28 UTC, RiscadoA requested changes
Thanks for working on this too @roby2014! So happy to see all of those `old::` things going away :sob:

2023-11-13 11:17 UTC, roby2014 commented on tools/tesseratos/src/tesseratos/settings_inspector/plugin.cpp
> +            inspector->inspect("Settings", mapType, &map, false);
Sorry, didnt understand this request

2023-11-13 11:22 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/settings_inspector/plugin.cpp
> +            inspector->inspect("Settings", mapType, &map, false);
Check out my review [here](https://github.com/GameDevTecnico/cubos/pull/779#discussion_r1390768611)

2023-11-14 08:15 UTC, RiscadoA approved these changes

2023-11-18 10:09 UTC, merged