Add a popup for selecting an asset of a given type
GameDevTecnico/cubos pull request #805
Opened 2023-11-12 20:26 UTC by roby2014

# Description

Add a popup function for selecting an asset of a given type, via `AssetExplorer` resource. This PR only implements the function, and not the usage in the plugins (like scene editor, etc)

## Checklist

- [X] Self-review changes.
- [X] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.

2023-11-13 09:19 UTC, RiscadoA requested changes
Thanks for working on this @roby2014! I mentioned in #779 that we would need to implement some way for users to add custom behavior to `DataInspector` later down the road - one use case for those would be here, in the asset explorer plugin. It could set hooks for `Asset` handles to show this popup instead of making users edit the UUID manually. We probably should open a tracking issue for work related to this, could you do that?

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    bool assetSelectionPopup(const std::string& title, cubos::engine::AnyAsset* selectedAssetBuffer,
Rename `selectedAssetBuffer` to `selectedAsset` and make it a reference - no need to use pointers here.

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    bool assetSelectionPopup(const std::string& title, cubos::engine::AnyAsset* selectedAssetBuffer,
Same as above

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +     * @param type The type of asset to filter.
Both of these docs should use the triple slash doc style

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +/// @ingroup tesseratos-asset-explorer-popup
Should be just `tesseratos-asset-explorer`

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +/// @brief @ref tesseratos-asset-explorer-popup utility file.
Should be `Function @ref tesseratos::assetSelectionPopup.`

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/plugin.hpp
> +
I think you no longer use this header here

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +                             const cubos::core::ecs::Read<cubos::engine::Assets>& assets)
In both of these functions take a reference to `Assets&` instead of `Read<Assets>`, see #404

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp
> +        for (auto const& a : assets->listAll())
I would rename `a` to `asset`

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp
> +                auto meta = assets->readMeta(a)->get("path");
`path` instead of `meta`

2023-11-13 09:19 UTC, RiscadoA commented on tools/tesseratos/src/tesseratos/asset_explorer/popup.cpp
> +                ImGui::Text("- %s", (*meta).c_str());
`path->c_str()`

2023-11-13 14:27 UTC, roby2014 commented
> Thanks for working on this @roby2014! I mentioned in #779 that we would need to implement some way for users to add custom behavior to `DataInspector` later down the road - one use case for those would be here, in the asset explorer plugin. It could set hooks for `Asset` handles to show this popup instead of making users edit the UUID manually. We probably should open a tracking issue for work related to this, could you do that?

Yep, opened tracking issue: #810

2023-11-18 18:16 UTC, RiscadoA approved these changes
LGTM :) have you tested this tho?

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    ///
```suggestion
```

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @param title The title of the popup.
```suggestion
    /// @param title Popup title.
```

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @param type The type of asset to filter.
```suggestion
    /// @param type Asset type to filter by.
```

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @param assets The assets database to query.
```suggestion
    /// @param assets Assets database to query.
```

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @return True if an asset is selected, false otherwise.
```suggestion
    /// @return Whether an asset is selected.
```

2023-11-18 18:16 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @param selectedAssetBuffer Pointer to store the selected asset.
```suggestion
    /// @param[out] selectedAssetBuffer Output asset.
```

2023-11-18 18:17 UTC, RiscadoA commented on tools/tesseratos/include/tesseratos/asset_explorer/popup.hpp
> +    /// @return True if an asset is selected, false otherwise.
Whoops, forgot to request changes here too.

2023-11-18 18:36 UTC, merged