Integrate screenPickerPlugin with rendererPlugin
GameDevTecnico/cubos pull request #897
Opened 2024-01-24 21:43 UTC by tomas7770

# Description

Draws entity indexes to the screenPickerPlugin framebuffer, allowing the plugin to actually work (for entities).

## Checklist

- [ ] Self-review changes.
- [ ] Evaluate impact on the documentation.
- [ ] Ensure test coverage.
- [ ] Write new samples.

2024-01-24 22:43 UTC, RiscadoA requested changes
Thanks for working on this! Overall LGTM, good work!

2024-01-24 22:43 UTC, RiscadoA commented on engine/include/cubos/engine/renderer/renderer.hpp
> +                    const RendererFrame& frame, const core::gl::Framebuffer& pickingBuffer, bool enableScreenPicking,
Instead of passing a boolean `enableScreenPicking`, you can set `pickingBuffer` to `nullptr` to disable it, as we do with `target`.

2024-01-24 22:43 UTC, RiscadoA commented on engine/src/cubos/engine/screenpicker/screenpicker.cpp
Just now noticed that we're using `screenpicker` as a path name, but shouldn't we use `screen_picker`, for consistency? Usually we add a underscore between words.

2024-01-25 17:20 UTC, tomas7770 commented on engine/src/cubos/engine/screenpicker/screenpicker.cpp
What about tags and settings? E.g. `cubos.screenpicker.init`, `cubos.renderer.screenpicking.enabled`. Underscore too?

2024-01-26 14:57 UTC, merged